"""ISO-3166-1-Alpha-2-Länder mit deutschem und englischem Namen.

Wird für die Länder-Auswahl (Combobox) verwendet: Anzeige = Klarname,
übermittelter Wert = ISO-Code. Gleiches {de,en}-Muster wie UNITS.
"""

COUNTRIES = [
    ("AF", {"de": "Afghanistan", "en": "Afghanistan"}),
    ("EG", {"de": "Ägypten", "en": "Egypt"}),
    ("AX", {"de": "Ålandinseln", "en": "Åland Islands"}),
    ("AL", {"de": "Albanien", "en": "Albania"}),
    ("DZ", {"de": "Algerien", "en": "Algeria"}),
    ("AS", {"de": "Amerikanisch-Samoa", "en": "American Samoa"}),
    ("AD", {"de": "Andorra", "en": "Andorra"}),
    ("AO", {"de": "Angola", "en": "Angola"}),
    ("AI", {"de": "Anguilla", "en": "Anguilla"}),
    ("AQ", {"de": "Antarktis", "en": "Antarctica"}),
    ("AG", {"de": "Antigua und Barbuda", "en": "Antigua and Barbuda"}),
    ("GQ", {"de": "Äquatorialguinea", "en": "Equatorial Guinea"}),
    ("AR", {"de": "Argentinien", "en": "Argentina"}),
    ("AM", {"de": "Armenien", "en": "Armenia"}),
    ("AW", {"de": "Aruba", "en": "Aruba"}),
    ("AZ", {"de": "Aserbaidschan", "en": "Azerbaijan"}),
    ("ET", {"de": "Äthiopien", "en": "Ethiopia"}),
    ("AU", {"de": "Australien", "en": "Australia"}),
    ("BS", {"de": "Bahamas", "en": "Bahamas"}),
    ("BH", {"de": "Bahrain", "en": "Bahrain"}),
    ("BD", {"de": "Bangladesch", "en": "Bangladesh"}),
    ("BB", {"de": "Barbados", "en": "Barbados"}),
    ("BY", {"de": "Belarus", "en": "Belarus"}),
    ("BE", {"de": "Belgien", "en": "Belgium"}),
    ("BZ", {"de": "Belize", "en": "Belize"}),
    ("BJ", {"de": "Benin", "en": "Benin"}),
    ("BM", {"de": "Bermuda", "en": "Bermuda"}),
    ("BT", {"de": "Bhutan", "en": "Bhutan"}),
    ("BO", {"de": "Bolivien", "en": "Bolivia"}),
    ("BQ", {"de": "Bonaire, Sint Eustatius und Saba",
            "en": "Bonaire, Sint Eustatius and Saba"}),
    ("BA", {"de": "Bosnien und Herzegowina", "en": "Bosnia and Herzegovina"}),
    ("BW", {"de": "Botswana", "en": "Botswana"}),
    ("BV", {"de": "Bouvetinsel", "en": "Bouvet Island"}),
    ("BR", {"de": "Brasilien", "en": "Brazil"}),
    ("IO", {"de": "Britisches Territorium im Indischen Ozean",
            "en": "British Indian Ocean Territory"}),
    ("BN", {"de": "Brunei Darussalam", "en": "Brunei Darussalam"}),
    ("BG", {"de": "Bulgarien", "en": "Bulgaria"}),
    ("BF", {"de": "Burkina Faso", "en": "Burkina Faso"}),
    ("BI", {"de": "Burundi", "en": "Burundi"}),
    ("CV", {"de": "Cabo Verde", "en": "Cabo Verde"}),
    ("CL", {"de": "Chile", "en": "Chile"}),
    ("CN", {"de": "China", "en": "China"}),
    ("CK", {"de": "Cookinseln", "en": "Cook Islands"}),
    ("CR", {"de": "Costa Rica", "en": "Costa Rica"}),
    ("CI", {"de": "Côte d’Ivoire", "en": "Côte d’Ivoire"}),
    ("CW", {"de": "Curaçao", "en": "Curaçao"}),
    ("DK", {"de": "Dänemark", "en": "Denmark"}),
    ("DE", {"de": "Deutschland", "en": "Germany"}),
    ("DM", {"de": "Dominica", "en": "Dominica"}),
    ("DO", {"de": "Dominikanische Republik", "en": "Dominican Republic"}),
    ("DJ", {"de": "Dschibuti", "en": "Djibouti"}),
    ("EC", {"de": "Ecuador", "en": "Ecuador"}),
    ("SV", {"de": "El Salvador", "en": "El Salvador"}),
    ("ER", {"de": "Eritrea", "en": "Eritrea"}),
    ("EE", {"de": "Estland", "en": "Estonia"}),
    ("SZ", {"de": "Eswatini", "en": "Eswatini"}),
    ("FK", {"de": "Falklandinseln", "en": "Falkland Islands"}),
    ("FO", {"de": "Färöer", "en": "Faroe Islands"}),
    ("FJ", {"de": "Fidschi", "en": "Fiji"}),
    ("FI", {"de": "Finnland", "en": "Finland"}),
    ("FR", {"de": "Frankreich", "en": "France"}),
    ("GF", {"de": "Französisch-Guayana", "en": "French Guiana"}),
    ("PF", {"de": "Französisch-Polynesien", "en": "French Polynesia"}),
    ("TF", {"de": "Französische Süd- und Antarktisgebiete",
            "en": "French Southern Territories"}),
    ("GA", {"de": "Gabun", "en": "Gabon"}),
    ("GM", {"de": "Gambia", "en": "Gambia"}),
    ("GE", {"de": "Georgien", "en": "Georgia"}),
    ("GH", {"de": "Ghana", "en": "Ghana"}),
    ("GI", {"de": "Gibraltar", "en": "Gibraltar"}),
    ("GD", {"de": "Grenada", "en": "Grenada"}),
    ("GR", {"de": "Griechenland", "en": "Greece"}),
    ("GL", {"de": "Grönland", "en": "Greenland"}),
    ("GP", {"de": "Guadeloupe", "en": "Guadeloupe"}),
    ("GU", {"de": "Guam", "en": "Guam"}),
    ("GT", {"de": "Guatemala", "en": "Guatemala"}),
    ("GG", {"de": "Guernsey", "en": "Guernsey"}),
    ("GN", {"de": "Guinea", "en": "Guinea"}),
    ("GW", {"de": "Guinea-Bissau", "en": "Guinea-Bissau"}),
    ("GY", {"de": "Guyana", "en": "Guyana"}),
    ("HT", {"de": "Haiti", "en": "Haiti"}),
    ("HM", {"de": "Heard und McDonaldinseln",
            "en": "Heard Island and McDonald Islands"}),
    ("HN", {"de": "Honduras", "en": "Honduras"}),
    ("HK", {"de": "Hongkong", "en": "Hong Kong"}),
    ("IN", {"de": "Indien", "en": "India"}),
    ("ID", {"de": "Indonesien", "en": "Indonesia"}),
    ("IQ", {"de": "Irak", "en": "Iraq"}),
    ("IR", {"de": "Iran", "en": "Iran"}),
    ("IE", {"de": "Irland", "en": "Ireland"}),
    ("IS", {"de": "Island", "en": "Iceland"}),
    ("IM", {"de": "Isle of Man", "en": "Isle of Man"}),
    ("IL", {"de": "Israel", "en": "Israel"}),
    ("IT", {"de": "Italien", "en": "Italy"}),
    ("JM", {"de": "Jamaika", "en": "Jamaica"}),
    ("JP", {"de": "Japan", "en": "Japan"}),
    ("YE", {"de": "Jemen", "en": "Yemen"}),
    ("JE", {"de": "Jersey", "en": "Jersey"}),
    ("JO", {"de": "Jordanien", "en": "Jordan"}),
    ("KY", {"de": "Kaimaninseln", "en": "Cayman Islands"}),
    ("KH", {"de": "Kambodscha", "en": "Cambodia"}),
    ("CM", {"de": "Kamerun", "en": "Cameroon"}),
    ("CA", {"de": "Kanada", "en": "Canada"}),
    ("KZ", {"de": "Kasachstan", "en": "Kazakhstan"}),
    ("QA", {"de": "Katar", "en": "Qatar"}),
    ("KE", {"de": "Kenia", "en": "Kenya"}),
    ("KG", {"de": "Kirgisistan", "en": "Kyrgyzstan"}),
    ("KI", {"de": "Kiribati", "en": "Kiribati"}),
    ("CC", {"de": "Kokosinseln", "en": "Cocos (Keeling) Islands"}),
    ("CO", {"de": "Kolumbien", "en": "Colombia"}),
    ("KM", {"de": "Komoren", "en": "Comoros"}),
    ("CD", {"de": "Kongo (Demokratische Republik)",
            "en": "Congo (Democratic Republic)"}),
    ("CG", {"de": "Kongo (Republik)", "en": "Congo (Republic)"}),
    ("HR", {"de": "Kroatien", "en": "Croatia"}),
    ("CU", {"de": "Kuba", "en": "Cuba"}),
    ("KW", {"de": "Kuwait", "en": "Kuwait"}),
    ("LA", {"de": "Laos", "en": "Laos"}),
    ("LS", {"de": "Lesotho", "en": "Lesotho"}),
    ("LV", {"de": "Lettland", "en": "Latvia"}),
    ("LB", {"de": "Libanon", "en": "Lebanon"}),
    ("LR", {"de": "Liberia", "en": "Liberia"}),
    ("LY", {"de": "Libyen", "en": "Libya"}),
    ("LI", {"de": "Liechtenstein", "en": "Liechtenstein"}),
    ("LT", {"de": "Litauen", "en": "Lithuania"}),
    ("LU", {"de": "Luxemburg", "en": "Luxembourg"}),
    ("MO", {"de": "Macau", "en": "Macao"}),
    ("MG", {"de": "Madagaskar", "en": "Madagascar"}),
    ("MW", {"de": "Malawi", "en": "Malawi"}),
    ("MY", {"de": "Malaysia", "en": "Malaysia"}),
    ("MV", {"de": "Malediven", "en": "Maldives"}),
    ("ML", {"de": "Mali", "en": "Mali"}),
    ("MT", {"de": "Malta", "en": "Malta"}),
    ("MA", {"de": "Marokko", "en": "Morocco"}),
    ("MH", {"de": "Marshallinseln", "en": "Marshall Islands"}),
    ("MQ", {"de": "Martinique", "en": "Martinique"}),
    ("MR", {"de": "Mauretanien", "en": "Mauritania"}),
    ("MU", {"de": "Mauritius", "en": "Mauritius"}),
    ("YT", {"de": "Mayotte", "en": "Mayotte"}),
    ("MX", {"de": "Mexiko", "en": "Mexico"}),
    ("FM", {"de": "Mikronesien", "en": "Micronesia"}),
    ("MD", {"de": "Moldau", "en": "Moldova"}),
    ("MC", {"de": "Monaco", "en": "Monaco"}),
    ("MN", {"de": "Mongolei", "en": "Mongolia"}),
    ("ME", {"de": "Montenegro", "en": "Montenegro"}),
    ("MS", {"de": "Montserrat", "en": "Montserrat"}),
    ("MZ", {"de": "Mosambik", "en": "Mozambique"}),
    ("MM", {"de": "Myanmar", "en": "Myanmar"}),
    ("NA", {"de": "Namibia", "en": "Namibia"}),
    ("NR", {"de": "Nauru", "en": "Nauru"}),
    ("NP", {"de": "Nepal", "en": "Nepal"}),
    ("NC", {"de": "Neukaledonien", "en": "New Caledonia"}),
    ("NZ", {"de": "Neuseeland", "en": "New Zealand"}),
    ("NI", {"de": "Nicaragua", "en": "Nicaragua"}),
    ("NL", {"de": "Niederlande", "en": "Netherlands"}),
    ("NE", {"de": "Niger", "en": "Niger"}),
    ("NG", {"de": "Nigeria", "en": "Nigeria"}),
    ("NU", {"de": "Niue", "en": "Niue"}),
    ("KP", {"de": "Nordkorea", "en": "North Korea"}),
    ("MK", {"de": "Nordmazedonien", "en": "North Macedonia"}),
    ("MP", {"de": "Nördliche Marianen", "en": "Northern Mariana Islands"}),
    ("NF", {"de": "Norfolkinsel", "en": "Norfolk Island"}),
    ("NO", {"de": "Norwegen", "en": "Norway"}),
    ("OM", {"de": "Oman", "en": "Oman"}),
    ("AT", {"de": "Österreich", "en": "Austria"}),
    ("PK", {"de": "Pakistan", "en": "Pakistan"}),
    ("PS", {"de": "Palästina", "en": "Palestine"}),
    ("PW", {"de": "Palau", "en": "Palau"}),
    ("PA", {"de": "Panama", "en": "Panama"}),
    ("PG", {"de": "Papua-Neuguinea", "en": "Papua New Guinea"}),
    ("PY", {"de": "Paraguay", "en": "Paraguay"}),
    ("PE", {"de": "Peru", "en": "Peru"}),
    ("PH", {"de": "Philippinen", "en": "Philippines"}),
    ("PN", {"de": "Pitcairninseln", "en": "Pitcairn"}),
    ("PL", {"de": "Polen", "en": "Poland"}),
    ("PT", {"de": "Portugal", "en": "Portugal"}),
    ("PR", {"de": "Puerto Rico", "en": "Puerto Rico"}),
    ("RE", {"de": "Réunion", "en": "Réunion"}),
    ("RW", {"de": "Ruanda", "en": "Rwanda"}),
    ("RO", {"de": "Rumänien", "en": "Romania"}),
    ("RU", {"de": "Russische Föderation", "en": "Russian Federation"}),
    ("SB", {"de": "Salomonen", "en": "Solomon Islands"}),
    ("ZM", {"de": "Sambia", "en": "Zambia"}),
    ("WS", {"de": "Samoa", "en": "Samoa"}),
    ("SM", {"de": "San Marino", "en": "San Marino"}),
    ("ST", {"de": "São Tomé und Príncipe", "en": "Sao Tome and Principe"}),
    ("SA", {"de": "Saudi-Arabien", "en": "Saudi Arabia"}),
    ("SE", {"de": "Schweden", "en": "Sweden"}),
    ("CH", {"de": "Schweiz", "en": "Switzerland"}),
    ("SN", {"de": "Senegal", "en": "Senegal"}),
    ("RS", {"de": "Serbien", "en": "Serbia"}),
    ("SC", {"de": "Seychellen", "en": "Seychelles"}),
    ("SL", {"de": "Sierra Leone", "en": "Sierra Leone"}),
    ("ZW", {"de": "Simbabwe", "en": "Zimbabwe"}),
    ("SG", {"de": "Singapur", "en": "Singapore"}),
    ("SX", {"de": "Sint Maarten", "en": "Sint Maarten"}),
    ("SK", {"de": "Slowakei", "en": "Slovakia"}),
    ("SI", {"de": "Slowenien", "en": "Slovenia"}),
    ("SO", {"de": "Somalia", "en": "Somalia"}),
    ("ES", {"de": "Spanien", "en": "Spain"}),
    ("LK", {"de": "Sri Lanka", "en": "Sri Lanka"}),
    ("BL", {"de": "Saint-Barthélemy", "en": "Saint Barthélemy"}),
    ("SH", {"de": "St. Helena", "en": "Saint Helena"}),
    ("KN", {"de": "St. Kitts und Nevis", "en": "Saint Kitts and Nevis"}),
    ("LC", {"de": "St. Lucia", "en": "Saint Lucia"}),
    ("MF", {"de": "Saint-Martin (franz. Teil)",
            "en": "Saint Martin (French part)"}),
    ("PM", {"de": "St. Pierre und Miquelon",
            "en": "Saint Pierre and Miquelon"}),
    ("VC", {"de": "St. Vincent und die Grenadinen",
            "en": "Saint Vincent and the Grenadines"}),
    ("SD", {"de": "Sudan", "en": "Sudan"}),
    ("SS", {"de": "Südsudan", "en": "South Sudan"}),
    ("ZA", {"de": "Südafrika", "en": "South Africa"}),
    ("GS", {"de": "Südgeorgien und die Südl. Sandwichinseln",
            "en": "South Georgia and the South Sandwich Islands"}),
    ("KR", {"de": "Südkorea", "en": "South Korea"}),
    ("SR", {"de": "Suriname", "en": "Suriname"}),
    ("SJ", {"de": "Spitzbergen und Jan Mayen", "en": "Svalbard and Jan Mayen"}),
    ("SY", {"de": "Syrien", "en": "Syria"}),
    ("TJ", {"de": "Tadschikistan", "en": "Tajikistan"}),
    ("TW", {"de": "Taiwan", "en": "Taiwan"}),
    ("TZ", {"de": "Tansania", "en": "Tanzania"}),
    ("TH", {"de": "Thailand", "en": "Thailand"}),
    ("TL", {"de": "Timor-Leste", "en": "Timor-Leste"}),
    ("TG", {"de": "Togo", "en": "Togo"}),
    ("TK", {"de": "Tokelau", "en": "Tokelau"}),
    ("TO", {"de": "Tonga", "en": "Tonga"}),
    ("TT", {"de": "Trinidad und Tobago", "en": "Trinidad and Tobago"}),
    ("TD", {"de": "Tschad", "en": "Chad"}),
    ("CZ", {"de": "Tschechien", "en": "Czechia"}),
    ("TN", {"de": "Tunesien", "en": "Tunisia"}),
    ("TR", {"de": "Türkei", "en": "Türkiye"}),
    ("TM", {"de": "Turkmenistan", "en": "Turkmenistan"}),
    ("TC", {"de": "Turks- und Caicosinseln",
            "en": "Turks and Caicos Islands"}),
    ("TV", {"de": "Tuvalu", "en": "Tuvalu"}),
    ("UG", {"de": "Uganda", "en": "Uganda"}),
    ("UA", {"de": "Ukraine", "en": "Ukraine"}),
    ("HU", {"de": "Ungarn", "en": "Hungary"}),
    ("UY", {"de": "Uruguay", "en": "Uruguay"}),
    ("UZ", {"de": "Usbekistan", "en": "Uzbekistan"}),
    ("VU", {"de": "Vanuatu", "en": "Vanuatu"}),
    ("VA", {"de": "Vatikanstadt", "en": "Vatican City"}),
    ("VE", {"de": "Venezuela", "en": "Venezuela"}),
    ("AE", {"de": "Vereinigte Arabische Emirate",
            "en": "United Arab Emirates"}),
    ("US", {"de": "Vereinigte Staaten", "en": "United States"}),
    ("GB", {"de": "Vereinigtes Königreich", "en": "United Kingdom"}),
    ("VN", {"de": "Vietnam", "en": "Vietnam"}),
    ("VG", {"de": "Virgin Islands (britisch)",
            "en": "Virgin Islands (British)"}),
    ("VI", {"de": "Virgin Islands (USA)", "en": "Virgin Islands (U.S.)"}),
    ("WF", {"de": "Wallis und Futuna", "en": "Wallis and Futuna"}),
    ("CX", {"de": "Weihnachtsinsel", "en": "Christmas Island"}),
    ("EH", {"de": "Westsahara", "en": "Western Sahara"}),
    ("CF", {"de": "Zentralafrikanische Republik",
            "en": "Central African Republic"}),
    ("CY", {"de": "Zypern", "en": "Cyprus"}),
]
